spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: newratings

server:
  port: 9093


eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:9094/eureka