server:
  port: 9092

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hotels
    username: postgres
    password: 1234
    hikari:
    # Additional hikari settings (if needed)
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  config:
    import: optional:configserver:http://localhost:9096

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:9094/eureka
